name: Changelog

on:
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: read

jobs:
  changelog-entry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate CHANGELOG update
        run: |
          tool/changelog/check_keepachangelog.sh \
            --base "${{ github.event.pull_request.base.sha }}" \
            --head "${{ github.event.pull_request.head.sha }}"
